# Docs
# https://github.com/softprops/action-gh-release

name: Release

on:
  workflow_dispatch:
  push:
    # branches: ["main"]
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            osname: linux
            asset_name: ${{ github.event.repository.name }}-linux.zip
          - os: windows-latest
            osname: windows
            asset_name: ${{ github.event.repository.name }}-windows.zip
          - os: macos-latest
            osname: macosx
            asset_name: ${{ github.event.repository.name }}-macosx.zip

    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: pip install -r requirements.txt pyinstaller

      - name: Create binary
        run: pyinstaller --clean --noconfirm --onefile --windowed --icon "./assets/icons/icon.ico" --add-data "./assets:assets" --name "myip-tray" main.py

      - name: Zip assets
        uses: vimtor/action-zip@v1.2
        with:
          files: dist/ .env
          dest: dist/${{ github.event.repository.name }}-${{ matrix.osname }}.zip

      - name: Make release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/${{ matrix.asset_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
          overwrite: true
          draft: true
